# Publish to PowerShell Gallery with this key
environment:
  NuGetApiKey:
    secure: VMvVbhuMaUTbI8WgnJH/WF7UBGwj261AgERGm25s21zQErHoIdwacoF3yd6OjIWh

image: Visual Studio 2017

# specify the cloned folder in upper case so the PSGallery upload is in this format
clone_folder: c:\projects\PSDocBuilder

# Skip on updates to the readme.
skip_commits:
  files:
  - README.md
  - CHANGELOG.md

build: false

test_script:
# Run tests against both PS Desktop and PS Core
- ps: '& powershell.exe ./build.ps1'
- ps: '& pwsh.exe ./build.ps1'
# Build local artifacts
- ps: Invoke-PSDeploy -Path ./deploy.psdeploy.ps1 -Recurse $false -Force -Tags AppVeyor

before_deploy:
- ps: Invoke-PSDeploy -Path ./deploy.psdeploy.ps1 -Recurse $false -Force -Tags Release

deploy:
- provider: GitHub
  auth_token:
    secure: xLTg9M5bqlSITC5gJHWUD4wOqP1QPsjMQSTiWdCZI68Iflp3lemZ9Au5riRvbZl
  artifact: /.*\.nupkg/
  force_update: true
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
