# Publish to PowerShell Gallery with this key
environment:
  global:
    NuGetApiKey:
      secure: VMvVbhuMaUTbI8WgnJH/WF7UBGwj261AgERGm25s21zQErHoIdwacoF3yd6OjIWh

  # Run tests on both PowerShell 5.1 and PowerShell 6
  matrix:
  - PS_EXE: powershell.exe
    DEPLOY_HOST: true
  - PS_EXE: pwsh.exe

image: Visual Studio 2017

# specify the cloned folder in upper case so the PSGallery upload is in this format
clone_folder: c:\projects\PSDocBuilder

# Skip on updates to the readme.
skip_commits:
  files:
  - README.md
  - CHANGELOG.md

build: false

test_script:
- ps: '& $env:PS_EXE ./build.ps1'

before_deploy:
- ps: Invoke-PSDeploy -Path ./deploy.psdeploy.ps1 -Recurse $false -Force -Tags Release

deploy:
- provider: GitHub
  auth_token:
    secure: xLTg9M5bqlSITC5gJHWUD4wOqP1QPsjMQSTiWdCZI68Iflp3lemZ9Au5riRvbZl
  artifact: /.*\.nupkg/
  force_update: true
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
    DEPLOY_HOST: true
